# Introduction

Flooding is a serious, rising risk in England [@ref-NationalRiskRegister2026; @ref-ManagingFloodRisk], and maintenance of flood defence infrastructure is an important mitigation for protecting welfare of citizens and the environment. This responsibility, including scheduling of thousands of inspections a year, falls to the Environment Agency (EA). Evaluation of the condition of flood defences is done by a three tier system of visual and manual engineering inspections, needing specific experience, local knowledge, and expertise of engineers [@ref-assetInspectionGuidance]. This project seeks to undertake research showing data driven approaches could improve efficacy in this task.  

This project aims to use open datasets that can cover the majority of flood defences in England to explore how machine learning (ML) prediction of condition grades of flood defence assets can be done. Identification, collection, and processing of appropriate datasets is within scope, as is design, training, and evaluation of ML classifiers. Within scope, methods of prediction using existing engineering information will be explored to provide comparisons for model outcomes. The project will provide both qualitative assessment of the degree to which inspection currently relies on hard-to-access domain expertise, and direct comparison with developed data-driven approaches.

The scope excludes policy recommendations, building workings tools for screening at risk assets, or validation of results against future asset inspections. The project aims to provide quantitative evaluations of how ML models results indicate feasibility of such tools being developed in future work. 

The project will determine whether existing engineering information in EA documentation is sufficient to build any form of early intervention recommendation tool, or whether new data-driven approaches are necessary. It will explore how ML approaches to predicting condition grades perform compared to methods derived from the EA's established heuristic deterioration curves, using condition grades of recent inspections, attained from the EA. This will be done in a reproducible way, hosted publicly to be repeated or extended by anyone.  

This report describes background research and active research tasks carried out before presenting the results of trained ML models and evaluating the created artifact. Chapter 4 describes the exploration and implementation of the heuristic deterioration models published by the Halcrow group. This is key to describing why data science approaches are necessary, and essential context for benchmarking their performance. Appendices of the report include attributions of data usage and AI usage, and data dictionaries to describe features.