# Research

## User Need and Rationale

Flooding in England is a significant risk, affecting citizen safety and wellbeing, damaging to the environment and incurring substantial costs, both material and economic [@ref-ImpactFloodRisk; @ref-beltranImpactFloodingProperty2019; @ref-ficarraStaffWorkingPaper]. All forms of flooding are deemed to have significant effect by the Cabinet Office UK National Risk Register report (@ref-NationalRiskRegister2026, chapter 4 pg. 180-185), which also details the EA's role in leading efforts preparing for and responding to flooding. 
The EA therefore has an unwieldy task: to assess, inspect, and maintain a large and aging system of flood defences while flood risks and impacts continue to change. The AIMS register [@ref-AIMSSpatialFlood] comprises 141,996 flood defence assets, of which 37,364 are maintained by the EA. Greenpeace Unearthed published an article in 2023 describing how many crucial flood defences were in an inadequate condition prior to major flooding in 2023 [@ref-unearthed2023]. Emma Hardy MP's response to Gideon Amos MP's written questions about flood control reveal that the EA schedules around 110,000 inspections per year, potentially increase to 165,000, and additionally that around 7.1% of assets currently fall below the target grade, indicating no improvement on the 7% figure put forward in the Greenpeace Unearthed article. The question asked specifically what the actual cost was of routine maintenance and capital repair on existing flood defences, and the lack of a direct answer in Hardy's response could indicate that the EA struggles to measure these data. [@ref-question-uin-112916; @ref-question-uin-112921; @ref-question-uin-112920].

Given the significant challenge that the EA faces to maintain and improve standards of flood preparedness, data-driven approaches to developing tools and processes that could improve upon or support existing measures should be explored. 
The artifact is a ML research pipeline that could lead to a tool meeting the above need when applied: e.g. screening assets to schedule upcoming inspections in order to direct resources towards those likely to find a deteriorated grade and therefore need further action.
The user is the EA, or more generally a flood defence asset manager, with responsibility for scheduling and carrying out routine inspection and maintenance, and therefore will desire to be able to schedule inspections proactively when there is a heightened chance that the result of inspection will be a condition grade below target. 
As described above, the EA currently commissions inspections in three tiers, where the first tier is mostly driven by the asset type, and higher tiers are driven by escalation based on outcomes. If the user had access to a tool that allowed them to know which assets where more likely to need escalation, then they could be more flexible in how inspections were scheduled and could make more efficient use of available resources to provide better outcomes for flood defence asset health. 

In order to have operational impact, the artifact will need to provide information to the user unobtainable using existing heuristic guidance. The underlying hypothesis is that, since it is trained on results of expert assessments, the ML model will encode some expert domain knowledge that trained engineers and local experts have, making it accessible to an asset manager operating at national scale. In order to assess the success of this tool, it's ability to predict asset condition grades will be compared to naïve baselines and to heuristic curves given in the Halcrow document. The project's research question is therefore: “*Does a machine learning approach to predicting flood defence condition grade improve on established heuristic baselines?*”. Additionally, results must demonstrate potential to be operationally useful in order to meet user need. This means that the results can be filtered and presented so that the assets with useful findings are identified, and that confidence in predictions is sufficient to replace or complement an existing part of flood defence maintenance process. 

## Literature

The EA designed a comprehensive and highly involved process for inspections to produce asset grades from 1 to 5, with 1 being an asset in perfect condition and 5 an asset in very poor condition [@ref-halcrow; @ref-aims-desc pg. 2]. The process combines visual inspections, engineering surveys, and specialist investigations [@ref-assetInspectionGuidance]. The goal of the EA is to be proactive in planning inspections based on risk of failure, rather than reacting to events indicating failed or deteriorated asset. The design of the inspection hierarchy is intended to be efficient, allowing tier 2 and 3 inspections (engineering surveys and specialist investigations) to be sought using information presented in routine tier 1 visual inspections. 

The established tools for predicting rate of deterioration of flood defence are heuristics presented in the Halcrow document [@ref-halcrow, pg. 4, table 1.1]. These are curves and tables that describe an asset's deterioration from grade 1 to 5 based on inputs including its type, local environment, material, and maintenance regime. Specific inputs may be different for different assets [@ref-halcrow, pg. 6, section 2.1, table 2.1]. These curves have been designed based on practitioner and asset manager experience, and while they are intended specifically for scheduling asset specific inspection and monitoring [@ref-halcrow, pg. 4, section 1], selecting all correct inputs for each asset explicitly requires engineering knowledge, local experience, and professional judgement [@ref-halcrow, pg. 9, section 2.2]. The curves themselves are data informed but not statistically fitted models of deterioration rates. 
Because of both the required expertise and form of required inputs, this project found that heuristics do not make for effective tools for predicting a current inspection outcome for all assets, nationally, using the publicly available registers and data sets. For example, selecting the correct decay rate band would require an engineer's insight into the asset and its specific exposure in its locality [@ref-halcrow section 2.3], and data such as the width of the an embankment crest or whether it has a reinforced base are not recorded for each asset in the AIMS dataset or an equivalent register maintained by the EA [@ref-halcrow, pg. 8; @ref-aims-desc pg. 4-5]. The report will show that sensible assumptions could not be found to make heuristic base prediction work at a national scale.

The prediction of infrastructure condition is an established problem that has widespread and well understood benefits, borne out by the existing literature presenting methods for more accurate, more efficient, or more timely solutions to this problem. These examples span different types of infrastructure and environments, but also share common themes. In many cases, ML has been identified as an appropriate technique for taking an existing register of infrastructure or an open dataset and trying to predict the rate of deterioration, the current condition, or the probability of the condition state changing.

@ref-fardDevelopmentUtilizationBridge2024 explored the use of a large dataset to predict the condition of the bridge decks in the USA, and employed ML models such as Random Forest, XGBoost, and ANNs. They found overall accuracies between 79.4% and 83.4% could be achieved, with F1 scores between 0.775 and 0.797. The motivation of this paper is similar to this project - predicting the condition grade could improve the efficacy of maintenance and repair planning. The scope of this project was national, as is the flood defence asset problem, although the National Bridge Inventory (their core dataset) comprises 319404 bridge decks - significantly larger than the usable AIMS data. Fard and Fard augmented their national register of infrastructure assets with multiple additional sources - traffic, climate - and used geospatial information science (GIS) and remote sensor sources to compile this. This is comparable to the collection of flood exposure, geological, climate, and geometry data from national archives and GIS sources for this project. Fard and Fard explored the relative importance of the different sources using permutation based variable importance techniques, whereas this project ueses SHAP analysis scores. 

Another paper focusing on a similar problem, also concerned with the condition state of bridges, was written by Mia and Kameshwar to explore how statistical methods and large datasets could be applied as an alternative to manually evaluated inspection reports [@ref-kameshwar2023]. This research also used the NBI dataset and achieved accuracy over 90%. Relevant to this flood defence asset project, this paper discusses the impact that a skewed dataset with a majority condition grade can have on ML models and how biases that arise from this can be mitigated.

Both of these projects use a high quality central dataset. NBI data is highly complete, and so any bridge with any missing field could be discarded and leave enough data for adequate training and testing to prove the efficacy of ML [@ref-kameshwar2023 pg. 5 section 2.1]. In particular, the age of the asset and proof of yearly inspections could be established. This is a point of difference from data available for the flood defence research, where the AIMS dataset seemed to indicated that the age variable was unreliable in some cases, and the data provided by EA via EIR highly redacted. 

There is also existing research directly related to flood defence condition estimation. Tarrant et al. seeks to identify damage and weakness in flood defences by making use of remote sensor data. In particular, they make use of Light Detection and Ranging (LIDAR) data to try and identify specific damage to embankments that could lower the condition grade [@ref-tarrantIdentifyingSignsWeakness2017]. The paper establishes two points important for this project: that flood defence grades can be driven by mechanisms such as ground movement; and that LiDAR data is one way that data can be collected for individual assets. A key difference is that the Tarrant research is done at an individual asset scale, making use of high resolution data. This project seeks to apply some of those learnings to all assets at a national scale. 
